### ISSUE TITLE
UX issue:  "only show when targeting matches" + no tags = ads don't run

### ISSUE THREAD

**Issue by Ivshti** [heyAuraDev/adex-platform#297]
**Describe the bug**
If you clicked "only show when targeting matches" and you have units with no tags, your campaign won't run

**Solution**
Ensure all units have tags by forcing users to select a category, starting with our most popular ones (e.g. video streaming, software, cryptocurrency).

Furthermore, select countries - in case you don't want to select individually, present preset options (tier 1, tier 2, etc.)

After that, you'd still be able to add tags

Finally, **ensure all slots** have a category set and therefore targeting tags

**Comment by alesinka** [comment]
something like this here:
![image](https://user-images.githubusercontent.com/24762344/73276193-f9600f00-41f0-11ea-8970-2585eafbacc9.png)

**Comment by vanina-iv** [comment]
Categories and Geolocation should have "None of the above" options that are hidden in the "Advanced" section - not sure how this will work with the current design - are these fields supposed to act as drop-downs? Drop-downs would be optimal here IMHO. 

In addition, there should be a message saying that if no targeting (tags, categories, geolocations, etc.) is selected, the campaign will not run. E.g. "Please set campaign targeting to continue". 

There should also be a tooltip explaining the score - a lot of people are genuinely confused by this. 

P.S. I'll add the categories lists and the country tiers a bit later, currently working on it.

**Comment by alesinka** [comment]
yes, all inputs act like dropdowns, there is an option with an arrow in the components, but in real life they are clear enough on hover, etc...
![image](https://user-images.githubusercontent.com/24762344/73360403-823b8100-42ab-11ea-9029-5c9e05b80f4a.png)

**Comment by vanina-iv** [comment]
[Country tiers](https://docs.google.com/spreadsheets/d/1S4lO80tHPQbggvk5NP4rkcbH0YDLvPNodGFgDBOIiMM/edit?usp=sharing) (based on the World Bank's data about purchasing power and income per capita)

**Comment by vanina-iv** [comment]
**Categories of existing publishers:** 

Adult entertainment
Computers
Crypto
Electronics
Lifestyle
News - Latin America
News - Bulgaria
Online game reviews
Online games
Science
Software development
Stremio
Television
Torrents
URL shortener
Video entertainment
YouTube converter

**Comment by dmngdsm** [comment]
I did a revision of our tags. First I started reading [the 400 tags ](https://github.com/AdExNetwork/adex-models/blob/master/src/tags.js)that are already implemented in the platform but then I saw the [621 Google Vision categories tags](https://github.com/AdExNetwork/adex-models/blob/master/src/googleVisionCategories.js) that we have for future implementation and really liked how well structured they are, so I decided to reduce them and probably replace the existing ones with a reduced list of Google Vision categories. 

Benefits: If we decide to implement Google Vision auto categorization at certain point we will have these ready categories.

Cons: If we decided to change the categories with the reduced list now, we have to force all publishers to re-integrate their ad slots with the new categories.


What I propose now is a list of 68 tags to choose from: 

{ '_id': "/Adult"},
{ '_id': "/Arts & Entertainment/Entertainment Industry/Film & TV Industry"},
{ '_id': "/Arts & Entertainment/Humor"},
{ '_id': "/Arts & Entertainment/Movies"},
{ '_id': "/Arts & Entertainment/Music & Audio"},
{ '_id': "/Arts & Entertainment/Visual Art & Design"},
{ '_id': "/Autos & Vehicles"},
{ '_id': "/Autos & Vehicles/Vehicle Shopping"},
{ '_id': "/Beauty & Fitness"},
{ '_id': "/Beauty & Fitness/Fashion & Style"},
{ '_id': "/Beauty & Fitness/Fitness"},
{ '_id': "/Books & Literature"},
{ '_id': "/Books & Literature/E-Books"},
{ '_id': "/Business & Industrial"},
{ '_id': "/Business & Industrial/Business & Economics"},
{ '_id': "/Computers & Electronics/Electronics & Electrical"},
{ '_id': "/Computers & Electronics/Programming"},
{ '_id': "/Computers & Electronics/Software"},
{ '_id': "/Finance"},
{ '_id': "/Finance/Credit & Lending"},
{ '_id': "/Finance/Insurance"},
{ '_id': "/Finance/Investing"},
{ '_id': "/Finance/Investing/Stocks, Bonds, Commodities & Futures Trading"},
{ '_id': "/Finance/Investing/Currencies & Foreign Exchange"},
{ '_id': "/Finance/Investing/Cryptocurrencies"},
{ '_id': "/Food & Drink"},
{ '_id': "/Games"},
{ '_id': "/Games/Poker & Casino Games"},
{ '_id': "/Games/Computer & Video Games"},
{ '_id': "/Games/Gambling"},
{ '_id': "/Games/Online Games"},
{ '_id': "/Health"},
{ '_id': "/Health/Men's Health"},
{ '_id': "/Health/Women's Health"},
{ '_id': "/Hobbies & Leisure"},
{ '_id': "/Home & Garden"},
{ '_id': "/Jobs & Education"},
{ '_id': "/Jobs & Education/Education"},
{ '_id': "/Jobs & Education/Jobs and Job Listings"},
{ '_id': "/News"},
{ '_id': "/News/Business News"},
{ '_id': "/News/Business News/Financial Markets News"},
{ '_id': "/News/Gossip & Tabloid News"},
{ '_id': "/News/Politics"},
{ '_id': "/News/Sports News"},
{ '_id': "/News/Weather"},
{ '_id': "/People & Society/Personal Blogs"},
{ '_id': "/Real Estate"},
{ '_id': "/Shopping"},
{ '_id': "/Shopping/Apparel"},
{ '_id': "/Shopping/Coupons & Discount Offers"},
{ '_id': "/Shopping/Luxury Goods"},
{ '_id': "/Sports"},
{ '_id': "/Sports/Combat Sports"},
{ '_id': "/Sports/Extreme Sports"},
{ '_id': "/Sports/Individual Sports"},
{ '_id': "/Sports/Motor Sports"},
{ '_id': "/Sports/Sporting Goods"},
{ '_id': "/Sports/Team Sports"},
{ '_id': "/Sports/Team Sports/American Football"},
{ '_id': "/Sports/Team Sports/Basketball"},
{ '_id': "/Sports/Team Sports/Soccer"},
{ '_id': "/Sports/Team Sports/Volleyball"},
{ '_id': "/Travel"},
{ '_id': "/Travel/Air Travel"},
{ '_id': "/Travel/Hotels & Accommodations"},
{ '_id': "/Travel/Tourist Destinations"},
{ '_id': "/Travel/Travel Blogs"}

**Comment by rori4** [comment]
If we implement the google vision the categorization can be done automatically.

This means that websites content will be auto categorized based on the content it has. This can be done in the backend. The banners categorization with the same tags was trickier. First google vision gives keywords that describe the image and then you can analyse those keywords to put them in the above categories, but overall worked quite well.

Here are some issues that I remember:
- websites with different language then English need to be translated first.
- for each page you want to display your ads you need to create another slot with the URL you want to categorize. This is not optimal. Maybe it should be done in ad-view level so you know where you display your current ad.

**Comment by ivopaunov** [comment]
Added with #437 :

* validation for at least one targeting for ad units
* validation on campaign checkbox "Only show ad if targeting matches" - can not continue if there are units with no targeting + Alert

**Comment by Ivshti** [comment]
Closing this as it's somewhat implemented and replaced by #468 and #405
