### ISSUE TITLE
If I Cancel Signing Up and Close login form app crashes

### ISSUE THREAD

**Issue by rori4** [heyAuraDev/adex-platform#302]
**Describe the bug**
If I try to login with metamask and I don't sign and then cancel the window the app throws ```Cannot read property 'address' of undefined```

**To Reproduce**
1. Go to login page
2. Click on login with metamask
3. Go and select an account to sign in with
4. When metamask pops up cancel signing
5. Cancel logging form
6. The app will crash

**Expected behavior**
Should not throw here

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5d7ace343a3e12000144232a/1f006c45-efe5-4584-93e4-4ce43f3e5a3d)

**Comment by ivopaunov** [comment]
I'm working on creating identity with external wallet and had the same issue. I'll fix it.
