### ISSUE TITLE
Make it possible to go back to available AdSlots/AdUnits from details view with with a back button

### ISSUE THREAD

**Issue by TRtomasz** [heyAuraDev/adex-platform#307]
**Is your feature request related to a problem? Please describe.**
Currently it is not possible to go back to the the list of the ad slots or ad units from details view.

**Describe the solution you'd like**
Simply add Back button or Close button. It is more intuitive then clicking again on  the item from the left side menu
**Describe alternatives you've considered**

**Additional context**
More context. It might be usefull in the following case. We have selected some elements and we also want to check details of one of them. Having to go back from details to the list by going through menu probably will restart selection

**Comment by Ivshti** [comment]
It's a UX decision to rely on clicking the back button of the browser

**Comment by TRtomasz** [comment]
I don't think it is 100% necessary to have this as long as https://github.com/AdExNetwork/adex-platform/issues/356 is done i will explain in #356 why i think it is good ux
