### ISSUE TITLE
Migrate to new the ENS registry

### ISSUE THREAD

**Issue by Ivshti** [heyAuraDev/adex-platform#312]
**Describe the bug**
See https://medium.com/the-ethereum-name-service/ens-registry-migration-bug-fix-new-features-64379193a5a
And https://docs.ens.domains/ens-migration/technical-description

**Steps**

* Change the ENS registry addr to the new one
* Notify ENS

**Comment by ivopaunov** [comment]
I'll just disable it for now

**Comment by rori4** [comment]
Here is the guide on what needs to be done: [https://docs.ens.domains/ens-migration/guide-for-dapp-developers](https://docs.ens.domains/ens-migration/guide-for-dapp-developers)

**Comment by Ivshti** [comment]
AFAIK we just have to change an address. Since we disabled it, there are no subdomains that we'd need to migrate
