### ISSUE TITLE
UI for picking the lead validator

### ISSUE THREAD

**Issue by Ivshti** [heyAuraDev/adex-platform#336]
**Is your feature request related to a problem? Please describe.**
We need a UI to pick the lead validator.

it will be implemented in later versions, but we need to start the design ASAP

It should be a table that will be embedded in the campaign modal.

The table should show all options, with their reputation score (which will be a %) and fees (again, in %). The user should be able to sort this by any means. We should also show an estimation of the campaign fees (e.g. if the campaign deposit is 200 DAI, and the fees are 5%, show "10 DAI" as campaign fees estimation)

There should be an extra button, "Add validator", which allows you to add your own URL of a validator. Keep in mind, if you paste an invalid URL, we should show an error (but the error does not need a design since we already have alerts)

**additional details, does not matter for design**
The reputation score should be a % of the largest pool's stake.

**Comment by alesinka** [comment]
In this case we have 3 popups in total, each with a dark overlay, i guess: 
![image](https://user-images.githubusercontent.com/24762344/75674474-c09ed400-5c8d-11ea-84fd-69b0625a62a0.png)

**Comment by Ivshti** [comment]
This is a decent start, but it will need a redesign when we eventally implement it, which won't be this year either most likely

**Comment by vanina-iv** [comment]
Checked with Ivo, outdated.
