### ISSUE TITLE
ENS updates with a delay (pending transactions not reflected)

### ISSUE THREAD

**Issue by vanina-iv** [heyAuraDev/adex-platform#340]
**Describe the bug**
When setting an ENS name, it takes a while for the name to be set; meanwhile, the platform allows you to set an ENS again (button is active and everything). 

**To Reproduce**
1. Go to platform.adex.network >> Account
2. Click on 'Set account ENS'
3. Confirm and sign transaction
4. ENS does not appear set immediately after that, takes some time + logging out and logging back in to see the ENS once transaction is accepted. 

**Expected behavior**
A message/icon saying "Pending" and perhaps a deactivated button for setting account ENS.

**Comment by Ivshti** [comment]
out of scope now, stuff like this will be handled by the Wallet
