### ISSUE TITLE
Backdate the platform changelog

### ISSUE THREAD

**Issue by vanina-iv** [heyAuraDev/adex-platform#342]
Please backdate the AdEx [platform changelog](https://github.com/AdExNetwork/adex-platform/blob/master/CHANGELOG.md) to make sure every significant change is recorded and documented. 

### Rationale
We are a distributed team and a changelog is crucial for the efficient functioning of the company, and of the marketing and communications team in particular. This is the optimal way to communicate important changes/bugfixes/improvements to the platform across the team. 

Paunov will take responsibility of keeping the changelog up to date from now on, but we need to fill in the gaps for the past couple of years.

**Comment by TRtomasz** [comment]
Staring from 2.2.2 changelog has not been updated. From 2.2.3 version number has not been updated until 4.0. Here is all i got starting from 2.2.2. If you think that anything particular is missing let me know
## 4.0.0
##### 2019.17.04

### Added
- Metamask address verification
- Networks and tokes configuration
- Contracts configuration
- Styles to identity step
- Fee token amount field
- Toast when metmask is not on mainnet 
- Possibility to select acount type
- Adex Identity support
- Coupon code validator
- Set targeting added to adunit view
- Toast on error with error message
- Grant account Login
- Adunit preview 
- Campaign preview
- IPFS images handling
- Camapign max deposit validation
- Date time picker for campaign creation

### Fixed
- Identity owner state
- Trezor signin 
- Image uploading
- Top bar

### Changed
- Account page view changed
- Dashboard view 

### Removed
- AirSwap
- Ledger signin

## 2.2.3
##### 2019.01.16

### Added 
- Sentry

### Fixed
- Legacy dapp browsers bug

## 2.2.2
##### 2019.01.07

### Changed
- we3 node changed to infura

### Fixed
- Getting address balance
- Random Seed Generator

**Comment by TRtomasz** [comment]
Here is more user friendly  change log version for 4.0. Although in my opinion it requires links to some articles/tutorial is couldn't find If this is fine i can go thorough commits starting from 4.0
## 4.0.0
##### 2019.04.17

### Added
- AdEx Identity Support. Users can use multiple devices or wallets for same AdEx Account
- Support of DAI and other (preapproved) ERC-20 tokens. Users no longer needs ETH to use AdEx
- Quick accounts: Users can create accounts with email and password /*here link with article about limitations and risks of quick account* - i couldnt find it/
- Reworked UX for publishers and advertisers. We have updated flow for creating AdUnits/Campaigns and AdSlots
- Uniswap supports. Users can swap their tokens to any of preapproved token with uniswap /* i can't find tract of uniswap in platform do we still use it? */
- Fiat money support. Now users can top up their account with GPB with ramp.network 

### Fixed
We have fixed multiple minor issues including:
- Trezor signin 
- Image uploading
- Top bar issues

### Removed
- AirSwap
- Ledger signin

**Comment by vanina-iv** [comment]
Thanks, Tomek @TRtomasz! I'll add this info to the changelog and we'll try to keep it up-to-date from now.

**Comment by TRtomasz** [comment]
What do you want to do with version for which i can't write anything? Should they stay in the change log in format where all fields empty or should they be removed?
## 4.10.17
##### 2020.02.02

### Added

### Fixed

### Changed

### Removed

**Comment by vanina-iv** [comment]
Done: https://github.com/AdExNetwork/adex-platform/pull/352
