### ISSUE TITLE
Missing edit button / feature for targeting tags on existing ad slots

### ISSUE THREAD

**Issue by TheBoroer** [heyAuraDev/adex-platform#349]
**Describe the bug**
I can't change the tags on an existing ad slot in the platform (edit icon/button is missing).
Adding tags manually into the iframe URL doesn't work either since the tags on the platform override the in-url targeting tags. I'd have to re-create all the ad-slots in order to add new tags in the future.

**To Reproduce**
1. Go to 'Ad Slots'
2. Click on any existing ad slot
3. Scroll down to 'tags'
4. See that there's no way to edit the tags on an existing ad slot

**Expected behavior**
I would have expected to be able to change the tags after creating the adslots, in case of misspellings or if I wanted to add more tags in the future.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 80.0.3987.116

**Comment by ivopaunov** [comment]
It's not a bug. It's a feature.
Same as https://github.com/AdExNetwork/adex-platform/issues/123

**Comment by ivopaunov** [comment]
Update: We are currently working on  targeting redesign where publishers won't be able to select ad tags, their websites will be categorized automatically.
