### ISSUE TITLE
Rename "Save Campaign" to "Start Campaign" when creating a campaign

### ISSUE THREAD

**Issue by TRtomasz** [heyAuraDev/adex-platform#351]
**Is your feature request related to a problem? Please describe.**
No it is not

**Describe the solution you'd like**
"Save Campaign" button should be renamed to "Start Campaign" as actually it is starting the campaign. Save does not indicate it will be started right after clicking the button

**Describe alternatives you've considered**

**Additional context**

**Comment by Ivshti** [comment]
This is not quite right, since the campaign might be scheduled for the future using the start date. 

It would be best if it's "schedule campaign" or "start campaign" depending on whether the start date is in the future

**Comment by vanina-iv** [comment]
I think "Save campaign" is just right - no need to rename that. Anyone who has ever worked with an ad platform will know what it is.
