### ISSUE TITLE
Frotend does not validate email address properly

### ISSUE THREAD

**Issue by TRtomasz** [heyAuraDev/adex-platform#354]
**Describe the bug**
It is possible to try to register email with characters outside the latin alphabet (ĄŻĆÓŁ...)

**To Reproduce**
1. Go to platform
2. Click on register
3. Scroll down to type email with characters outside latin alphabet
4. Relayer will return internal server error
5. Try to log in using that email address
6. Relayer will return 500 error

**Expected behavior**
1. Verify email adress characters
2. If account creating is not successful do not add email to the user logins list visible on the right side

**Screenshots**
![image](https://user-images.githubusercontent.com/40594253/75192807-4afaab80-5755-11ea-8d88-7f81474d1258.png)

![image](https://user-images.githubusercontent.com/40594253/75192829-56e66d80-5755-11ea-84f4-1593992fcd80.png)

**Comment by ivopaunov** [comment]
reopen it because it was not fixed correctly with https://github.com/AdExNetwork/adex-platform/pull/368/commits/5df81930db1dc73bf31a3506e0729f03e2310b4c

**Comment by IvoPaunov** [comment]
Reopen this because it was not fixed correctly with https://github.com/AdExNetwork/adex-platform/pull/368/commits/5df81930db1dc73bf31a3506e0729f03e2310b4c
