### ISSUE TITLE
Remember user filtering/sorting/pagination

### ISSUE THREAD

**Issue by TRtomasz** [heyAuraDev/adex-platform#356]
**Is your feature request related to a problem? Please describe.**
AdEx application does not remember user peferences regarding tables
**Describe the solution you'd like**
User preferences should be remembered so every time he opens the table view he will see it in the same order as the last time 

**Describe alternatives you've considered**

**Additional context**

**Comment by Ivshti** [comment]
I'm not that sure this is important, so I'm going to leave it unassigned/without a project

**Comment by TRtomasz** [comment]
I think it is really important. 
After some time users will have a lot of ad units, campaigns, ad slots. So it will be crucial for them to see only relevant elements in the correct order right from the moment they open the application without having to filter/reorder/set pagination every time. 
Whats more, i think it should be possible to save filters so they can have a set of saved filters in case they want to switch from one set of campaigns/ad slots to other set of campaigns. 
Filters also could be applied to the analytics charts so users can track data for specific campaigns/ad slots only.

**Comment by ivopaunov** [comment]
Closing in favor of https://github.com/AdExNetwork/adex-platform/issues/492
