### ISSUE TITLE
Receipt paid amount does not include fee

### ISSUE THREAD

**Issue by TRtomasz** [heyAuraDev/adex-platform#357]
**Describe the bug**
Generated receipt does not include fee in "Paid" field

**To Reproduce**
1. Go to campaigns
2. Display a receipt for a campaign
3. When 0% of the campaign budget has been distributed it displayes "NaN"

**Expected behavior**
It should never display NaN or even 0 because there is also transaction fee user paid in order to open a campaign

**Screenshots**
![image](https://user-images.githubusercontent.com/40594253/75195899-27d2fa80-575b-11ea-993f-6a40fb70618a.png)

**Desktop (please complete the following information):**
Latest Chrome/ Windows 10

**Comment by rori4** [comment]
It shows NaN because the fix in market hasn't been deployed. As for the fee it is a good idea to add it.

**Comment by Ivshti** [comment]
@IvoPaunov what's the status of this?
