### ISSUE TITLE
Platform left navbar hover issue

### ISSUE THREAD

**Issue by DimoStoyanov** [heyAuraDev/adex-platform#363]
**Describe the bug**
Once you log in to AdEx and hover over the selected item of the left navbar (dashboard / campaigns.. etc)  its background gets gray and weird. If you click on any item, that gets fixed. Once you refresh the page, brakes again.

**To Reproduce**
1. Log into your account
2. Hover over Dashboard on the left navbar

**Comment by rori4** [comment]
I noticed this yesterday and it is fixed with #49 in ui-improvements branch
