### ISSUE TITLE
Revenue data points missing on new accounts with no data

### ISSUE THREAD

**Issue by rori4** [heyAuraDev/adex-platform#367]
**Describe the bug**
There are no revenue data points on new accounts with no data.
![missing datapints revenue ](https://user-images.githubusercontent.com/22402693/75552595-4f69e180-5a3f-11ea-8a6e-300a17a28664.png)

**To Reproduce**
1. Create a new account or log to one with no publisher data
2. Go to publisher side
3. See there are no data points for revenue

**Expected behavior**
Zero datapoints should be added if there is no data

**Comment by ivopaunov** [comment]
It's not a BUG it's a FEATURE.
They were removed on purpose because  there are cases when there is no sufficient revenue to cover the withdraw taxes and we show nothing instead 0.
