### ISSUE TITLE
Close campaign UX issues

### ISSUE THREAD

**Issue by Ivshti** [heyAuraDev/adex-platform#369]
**Describe the bug**
Closing a campaign is quite confusing for a few reasons

* the button is not noticable; I suggest making it solid (contained) and bigger; also, clicking the media should open the campaign detail page (the same page that "view" opens)
* the status does not update immediately after pressing "close" 
* the Close button keeps showing after the campaign is in a Closed status
* it takes a few mins for the funds to show up, so a toast "Your campaign has been closed. The remaining funds will be returned to you in a few minutes." would be nice

slightly related:
* before a campaign is done, show the Report button but with a tooltip that says "Report not available until the campaign is completed"; otherwise the user does not know why the button exists in some cases and not in others

SUMMARY TODO (Rangel):
- [x] make button contained
- [x] make button bigger
- [x] media should open campaign detail page
- [x] update status immediately after pressing close
- [x] notify user "Your campaign has been closed. The remaining funds will be returned to you in a few minutes."
- [x] show receipt button when campaign not completed with tooltip "Report not available until the campaign is completed"

**Comment by rori4** [comment]
@Ivshti Should the media click on AdUnit and AdSlot go to detail page as well?
