### ISSUE TITLE
Campaign statistics: ad slot revenue breakdown by impressions/clicks/CTR 

### ISSUE THREAD

**Issue by dmngdsm** [heyAuraDev/adex-platform#370]
**Is your feature request related to a problem? Please describe.**
If you're a publisher, it's impossible to tell which ad slots are earning the most and see where your revenue's coming from.

Suggesting this for v4.1, correct me if it's impossible

**Describe the solution you'd like**
When you open an ad slot, a graph with stats like the one per account should be visible for the ad slot. Alternatively, on the dashboard you should be able to switch between the general stats per account and stats per single slots

**Describe alternatives you've considered**

**Comment by Ivshti** [comment]
@IvoPaunov this can be implemented via `reportPublishetToAdSlot`
