### ISSUE TITLE
Disclaimer about programmatic ad market principles/unpredictability

### ISSUE THREAD

**Issue by Ivshti** [heyAuraDev/adex-platform#374]
**Is your feature request related to a problem? Please describe.**
Users are often confused about varying impression numbers and the reasons behind this. We need to try to explain the reasons, especially considering our commitment to transparency.

**Describe the solution you'd like**
When you start using the platform as a publisher, a disclaimer should appear that explains why your impression count may not be consistent, even if your traffic is:

* Changes in the ad market (new campaigns with different targeting being opened/closed)
* Changes in how much advertisers pay (after AIP#6, advertisers will be able to dynamically change impression price per publisher)
* Changes in ad policies: e.g. changes in how impressions are counted (technically speaking, changes in Market and AdView)

**Describe alternatives you've considered**
Later on, we should:
* come up with an UI that illustrates the changes in the market: primarily campaigns that you're earning from that have ran out/closed
* announce ad policy changes in a changelog available on the Platform

**Comment by vanina-iv** [comment]
As for UI, what do you think of a section below the big impressions chart on the dashboard that says: _Your impression count is varying? Learn more about this._

The "Learn more" part will be a link to the blogpost explaining it. 

In addition, we can add a column in the "Best performing ads" table that shows the campaign status for the particular ad to illustrate if it's active or not.

**Comment by vanina-iv** [comment]
The blogpost is live now: https://www.adex.network/blog/varying-impression-count/

**Comment by Ivshti** [comment]
This is quite stuck, assigning @rori4

**Comment by vanina-iv** [comment]
Checked with Ivo, outdated.
