### ISSUE TITLE
UI: Add "Top Up" button with clear instructions

### ISSUE THREAD

**Issue by dmngdsm** [heyAuraDev/adex-platform#380]
**Is your feature request related to a problem? Please describe.**
There is no "Top Up" button or instructions on the platform at the moment. We have to rely on advertisers' common sense to know that they have to send funds to their address.

**Describe the solution you'd like**
I think there should be a button "Top Up with DAI" that just opens a popup with the address to copy and short instructions what to do. 

Simple implementation: Standard button above "Top Up with GBP" on Account page.
Not so simple implementation: Additionally to the button on Account page, we may put a button in upper left corner somewhere around the Account funds stats.

![Screenshot 2020-03-04 at 14 51 30](https://user-images.githubusercontent.com/15030734/75882249-76525a00-5e29-11ea-941b-547738fdcba9.png)

**Describe alternatives you've considered**
no

**Comment by ivopaunov** [comment]
https://github.com/AdExNetwork/adex-platform/issues/279
