### ISSUE TITLE
There is discrepancy in the campaigns view between % of served and real number of impressions

### ISSUE THREAD

**Issue by TRtomasz** [heyAuraDev/adex-platform#384]
**Describe the bug**
As you can see on the screenshot. It says that 100% of campaigns has been served although there are 0 clicks and impressions.
**To Reproduce**
1. log in 
2. go to campaigns list
user privileges to that identity were added for @IvoPaunov  and @rori4 so they can check from their accounts 
**Expected behavior**
% of served should be displayed correctly 

**Screenshots**
![image](https://user-images.githubusercontent.com/40594253/75968129-35138600-5ecd-11ea-98d0-e58a5eb94ada.png)

**Desktop (please complete the following information):**
-Windows 10
latest chrome

**Additional context**

**Comment by ivopaunov** [comment]
There are no impressions at all.
The campaign was expired without impressions.
Then the relayer auto closed the campaign - send close message to the validator.
Maybe we should think about status message, served % or something else.
When campaign is auto closed we have to send message to the market as it is manually closed or add different status - "Closed expired".

**Comment by Ivshti** [comment]
this is either fixed or was not a bug apparently
