### ISSUE TITLE
Changes to the tutorial

### ISSUE THREAD

**Issue by TRtomasz** [heyAuraDev/adex-platform#390]
**Is your feature request related to a problem? Please describe.**
It is related to the problems i encountered while checking tutorial.
1. Part after email confirmation isn't responsive i had to relog in order to see that i completed that step.
2. Dashed line should change color/look in order to indicate which step should be now done. I think that gold circles around steps are not indicating that good enough. 
3. First tutorial says `Go to your Advertiser dashboard and click the “New Ad unit” button.` - it is wrong because in Dashboard there is no such button it is under "Ad Units" tab
4. Next step is called "Fund your account" i guess "Top up your account" would be better
5. Fund your account tutorial chapter says `On your Dashboard, go to Account in the lower left corner of the screen.` Dashboard is Part with charts and tables. I guess better would be "Click Account from the bottom of the left side menu"
6. Tutorial says `On your Account screen you will see your **Identity address**, the address that you are using to login and the balance on your Identity address.`  a. We don't user that address to login b. rephrase `balance on your identity address` to `balance available...` There is no **Identity address** label in the Account view, two options a) Add **Identity Address* next to `AdEx account` or rephrase to `AdEx account address` 
7. Tutorial says `Now that you have it, just send funds to it using your preferred wallet.` we should mention what currency is preffered/approved
8. Creating campaign tutorial last sentence says `Your campaign is now created and it will start running whenever the “Start date” is set.shoudl be `it will start running when the "Start date" is met`
9. After finishing all steps there should be better notification about that everyting is done, maybe a popup with a link to the helpdesk/tutorials. Right now it is hard to notice that we are done.

**Additional context**
![image](https://user-images.githubusercontent.com/40594253/76065081-30150c00-5f8b-11ea-810b-8f2d1268d220.png)

**Comment by vanina-iv** [comment]
1. I didn't understand what you mean here - can you please explain? 

2. Not necessary. You can complete the steps in different order so let's not touch the dashed line.

3. We'll fix this. 

4. You can't top up something you've never funded, can you? Either way, let's not get too anal about tiny/irrelevant things like that. 

5. Again, let's not get anal about such things. It's not rocket science, people will figure it out.

6. You DO use the identity address to log in. We'll fix the Identity address to say "AdEx account".

7. No need. 

8. Again, I don't understand what you mean. If you want us to change "set" to "met", that's just not necessary, not to mention how confusing it sounds. 

9. Not necessary. 

Overall, let's keep an eye on the end game here. The purpose of this guide is to get people invested, to get them interested in the platform and keep them there. Hence the pop-up tutorials. We still have proper tutorials with images and whatnot in the help section. 

I don't think we should be wasting time changing a word to a synonym or being excessively descriptive. It's an ad network, we're not launching a rocket in space. Nobody has **ever** had a problem finding their account when we tell them it's in the lower left corner or the dashboard. Obsessing over things like that is simply an inefficient use of our time.

**Comment by TRtomasz** [comment]
Re 1.
1.Create new account, leave that tab open
2. Open email in new tab, click confirmation email there
3. Go back to the first tab 
4. Tutorial step with email confirmation isn't refreshed still says that you should confirm your email

**Comment by Ivshti** [comment]
1 - perhaps you mean that it doesn't update dynamically

2 - Agreed with Vanina, it's unordered

4 - yeah, no point - it doesn't matter

5 - I actually agree on 5, it's a bit annoying 

6 - yeah, "AdEx account" should be used everywhere; and "available balance"

8 - I agree that the current situation is confusing, how about "the start date has commenced"

**Comment by vanina-iv** [comment]
Let's make the following changes @rori4: 

#### Advertisers Getting started tutorials > Step 2 **Create an ad unit**

| Is currently  | Needs to become |
| ------------- | ------------- |
| 1. Go to your Advertiser dashboard and click the “New Ad unit” button.  | 1. Go to your Advertiser dashboard > Ad Units and click the “New Ad unit” button. |

#### Advertisers Getting started tutorials > Step 3 **Fund your account**  

| Is currently  | Needs to become |
| ------------- | ------------- |
| 1. On your Dashboard, go to Account in the lower left corner of the screen. | 1. Click on Account in the lower left corner of the screen. |
| 2. On your Account screen you will see your Identity address, the address that you are using to login and the balance on your Identity address. | 2. On your Account screen you will see your AdEx account and your available balance. |
| 3. Now that you have it, just send funds to it using your preferred wallet.. | 3. Now that you have it, just send DAI to it using your preferred wallet. Please note that you can only send DAI to your AdEx account. |

#### Advertisers Getting started tutorials > Step 4 **Launch your first campaign**  

| Is currently  | Needs to become |
| ------------- | ------------- |
| Your campaign is now created and it will start running whenever the “Start date” is set.  | Your campaign is now created and it will start running on the “Start date” you have set. |

#### Publishers/Advertisers Getting started > Step 1 **Confirm your email address**  

| Is currently  | Needs to become |
| ------------- | ------------- |
| Welcome to the platform. Let's first confirm your email!Go to adex.network and confirm your email!  | Welcome to the platform. Let's first confirm your email! Check your inbox for the confirmation link. |

![confirm email](https://user-images.githubusercontent.com/8737960/76099026-2a431900-5fd3-11ea-9986-a2ee24cbabe0.jpeg)
