### ISSUE TITLE
Targeting: ability to create a campaign only for certain publishers

### ISSUE THREAD

**Issue by Ivshti** [heyAuraDev/adex-platform#403]
**Is your feature request related to a problem? Please describe.**
Even with proper targeting tags, this still doesn't guarantee you'll only spend money on the relevant publishers

**Describe the solution you'd like**
In the targeting settings, be able to choose "Only show to select publishers" (or "recommended publishers"), which, when enabled, asks you which group of publishers you'd like (e.g. "faucets", "crypto news sites", "entertainment sites"). 

**EDIT:** in the context of AIP31, those can be added as "categories" of publishers that can be added, the same way that tiers of countries can be added

**Additional context**

Depends on:

* [Validator implementation of AIP6](https://github.com/AdExNetwork/adex-validator/issues/16) https://github.com/AdExNetwork/aips/issues/6
* Market: generate/hardcode the pre-made lists
* Market: pull mutable payments info from the validators and adjust it's results based on it (AIP#6)

**PLEASE NOTE:** this does not require the mutability/dynamic aspect of AIP#6. It only requires the ability to specify different prices for different publishers. It's not possible to make the list update dynamically, cause the Market is not authorized to change the campaign criteria on behalf of users.

**Comment by ivopaunov** [comment]
done in https://github.com/AdExNetwork/adex-platform/issues/468 based on AIP31 https://github.com/AdExNetwork/aips/issues/31
