### ISSUE TITLE
Тhe Getting started progress module looks like a rating module

### ISSUE THREAD

**Issue by DimoStoyanov** [heyAuraDev/adex-platform#409]
**Is your feature request related to a problem? Please describe.**
Having the **stars** in the progress module for publishers and advertisers looks more like a rating system. 

![Screenshot_2020-03-23 AdEx Platform(1)](https://user-images.githubusercontent.com/5999924/77317425-d4c97480-6d13-11ea-902e-808dddf4e77e.png)
![Screenshot_2020-03-23 AdEx Platform](https://user-images.githubusercontent.com/5999924/77317428-d5620b00-6d13-11ea-8939-49d401288ff7.png)

**Describe the solution you'd like**
We can simply swap the stars with checkmarks.

**Comment by vanina-iv** [comment]
That's intentional - urges people to collect all the stars and follow all the steps in the guide.

**Comment by DimoStoyanov** [comment]
Stars are used to rate things. Checkmarks are used when something is completed.

**Comment by Ivshti** [comment]
I agree re checkmarks. i was confused by the stars too the first time I saw them, they really don't convey the message

**Comment by vanina-iv** [comment]
It's not the obvious decision but it helps get people engaged with the platform. 

What you're saying is the effect we were going for - subconsciously "tell" people that if they complete all the steps, they get a higher status/rating.

**Comment by DimoStoyanov** [comment]
This basically is a getting started **Process** where we guide them how to place ad/slot.

If it was a gamification thing and we reward them for completing something, it will make sense to have a Trophy / Star at the _end of the process_. Even in this case the separate stages will have to be marked with checkmarks.

**Comment by vanina-iv** [comment]
The initial plan was to receive a small bonus when you complete the steps, i.e. get a reward when you collect all the stars. The bonus thing was then placed on hold. 

If you insist, we can change to checkmarks. I'm not married to the stars.

**Comment by Ivshti** [comment]
even with the bonus, I think checkmarks are more intuitive

**Comment by rori4** [comment]
I also want to change the text color to be black again and to have for the different sides the main color as background. Like this: 
![getting started pub](https://user-images.githubusercontent.com/22402693/78021648-4630a500-735c-11ea-873c-544022e755bb.png)
![getting started adv](https://user-images.githubusercontent.com/22402693/78021652-46c93b80-735c-11ea-80fc-5b3cabf6b7fe.png)
Let me know what you guys think @Ivshti @DimoStoyanov @vanina-iv @alesinka
P.S: The down arrow will also be white, just forgot about it

**Comment by Ivshti** [comment]
I like it, however the chevron on the right is barely visible 
EDIT: I see you covered that

**Comment by vanina-iv** [comment]
I like it.
