### ISSUE TITLE
Publisher / Advertiser tabs color scheme improvement

### ISSUE THREAD

**Issue by DimoStoyanov** [heyAuraDev/adex-platform#410]
**Is your feature request related to a problem? Please describe.**
I still find the colors we use for Publisher too light. 
The color we use for _advertisers_ is too bright compared to the one for _publishers_
Such a combination is used to point/illustrate active/inactive states of UI components.

**Describe the solution you'd like**
We need to make the publishers tab color and the Getting Started text color more intense and saturate. If we do not have a such color, we can add it.

![Screenshot_2020-03-23 AdEx Platform(3)](https://user-images.githubusercontent.com/5999924/77318549-ead83480-6d15-11ea-9082-98845a1aac4d.png)

- - -
some space between images
- - -

![Screenshot_2020-03-23 AdEx Platform(2)](https://user-images.githubusercontent.com/5999924/77318552-eb70cb00-6d15-11ea-9853-7057f88905de.png)

**Comment by rori4** [comment]
@DimoStoyanov I have made the colors more saturated as I showed you when we were in the office and this is in a PR #402
Currently Paunov is taking a look at the PR.

**Comment by rori4** [comment]
![publisher](https://user-images.githubusercontent.com/22402693/77418103-1b2fd980-6dcf-11ea-98c9-7803e7845e7e.png)
![advertiser](https://user-images.githubusercontent.com/22402693/77418109-1cf99d00-6dcf-11ea-9849-caafb4d6973e.png)

Here are how the publisher and advertiser side look like at the moment in the PR. Let me know if we need to change the colors @DimoStoyanov

**Comment by alesinka** [comment]
![image](https://user-images.githubusercontent.com/24762344/77650912-b3b38e80-6f74-11ea-990c-4c03f974f85d.png)

**Comment by DimoStoyanov** [comment]
Great. The colors look good - good contrast.

**Comment by ivopaunov** [comment]
This green is the worst

**Comment by Ivshti** [comment]
Seems to be implemented now

**Comment by rori4** [comment]
reopening as this needs to be referenced in the pull request where it's implemented. Doesn't seem to be implemented on staging or platform
