### ISSUE TITLE
Statistics about which ad slots you are earning the most from

### ISSUE THREAD

**Issue by vanina-iv** [heyAuraDev/adex-platform#414]
It will be useful for publishers to see which ad slots/positions bring them the most revenue - can we implement this?

**Comment by dmngdsm** [comment]
Related: Publishers should be able to see the same level of stats per ad slot as adveritsers (without the advertisers): Impressions, CTR, CPM.

**Comment by ivopaunov** [comment]
It is done #439,  Duplicated with #370 
![image](https://user-images.githubusercontent.com/10422618/80398423-43c05d00-88c0-11ea-8a1e-b04d7228a154.png)
