### ISSUE TITLE
Account Privileges structure change 

### ISSUE THREAD

**Issue by dmngdsm** [heyAuraDev/adex-platform#422]
**Is your feature request related to a problem? Please describe.**
Compared to how other networks, e.g. Google ads/analytics work, I feel there's "Analytics/View" account privileges type missing. Based on this I suggest the types of accounts privileges to be the following:

**Describe the solution you'd like**

| Privileges type | View Account and stats | Run ads | Deposit | Withdraw | Change privileges |
| ------------- | ------------- |------------ |------------ |------------ |------------ |
| None | No  | No | Yes | No | No |
|Viewer  | Yes  | No | Yes | No | No |
| Manager  | Yes  | Yes | Yes | No | No |
| Owner | Yes  | Yes | Yes | Yes | Yes |

**Describe alternatives you've considered**
View-only privileges are important for agencies for example, who want to show stats to clients, etc.

**Additional context**

**Comment by rori4** [comment]
Adding more privileges means that we need to change the identity contract
EDIT: 
My bad. There is a privilege for withdrawing
