### ISSUE TITLE
Use the Platform Landing Page left side as a Landing Page for campaigns

### ISSUE THREAD

**Issue by dmngdsm** [heyAuraDev/adex-platform#423]
**Is your feature request related to a problem? Please describe.**
When we launch campaigns we either link banner ads to the blog post announcements or directly to the AdEx platform.
Problem is that journey from landing on the blog to the platform is too long and if people land on the platform they don't get the information related to the platform and incentive for registering is not good enough. 

**Describe the solution you'd like**
Create mirrors of platform.adex.network in which the right sidebar with login options stays the same, but the left side is customized according to the specific campaign. 

Why mirrors? So that we don't confuse existing users and we can track conversions even better by using unique pages per campaign.

**Describe alternatives you've considered**

**Additional context**
Two super ugly mockups just to illustrate:

![landing-page](https://user-images.githubusercontent.com/15030734/78556868-74106080-7818-11ea-9a87-322ae456f5d1.jpg)
![landing-page-3](https://user-images.githubusercontent.com/15030734/78556876-770b5100-7818-11ea-92bb-da7565f4969d.jpg)

**Comment by dmngdsm** [comment]
After discussing with Ivo some concerns arose, as if so short conversion is actually people will be ready for, but anyway it's a good idea to to A/B testing for some of next campaigns. Also sidebar should actually be slicker - there's no need for any other buttons than "Create Account". The white space left can be utilized for giving more information to the user about the platform, so that we can convince them to register using only the landing page. I'd really like to do an A/B testing for this idea:


![landing-page-4](https://user-images.githubusercontent.com/15030734/78558595-8f309f80-781b-11ea-9305-be0d74ea9a2c.jpg)

**Comment by Ivshti** [comment]
@dmngdsm I assume this is still relevant even though we're not doing cashbacks?

**Comment by dmngdsm** [comment]
> @dmngdsm I assume this is still relevant even though we're not doing cashbacks?

absolutely, I believe we should utilize this space

**Comment by vanina-iv** [comment]
We can place a couple of case studies there - one for publishers and one for advertisers. Or place an ad for the wallet when we launch it.
