### ISSUE TITLE
Exclude own ads setting

### ISSUE THREAD

**Issue by dmngdsm** [heyAuraDev/adex-platform#424]
**Is your feature request related to a problem? Please describe.**
We now have a publisher on the platform who is also an advertiser and is afraid that his own banners might show up on his inventory

**Describe the solution you'd like**

When you are are starting an ad campaign or you are registering own ad slots, you should be able to opt out: "Run my own ads". I guess it will be more challenging on the technical level.

**Additional context**
![image](https://user-images.githubusercontent.com/15030734/78644855-3f0b1900-78bf-11ea-89e2-0efbe39134ec.png)

**Comment by Ivshti** [comment]
done with https://github.com/AdExNetwork/adex-adview-manager/commit/c8c804f818cbc91f45b7dc7c3b95a601c752a553

currently not an option but I don't think it needs to be: I don't see reasonable use cases for wanting to allow this behavior
