### ISSUE TITLE
UX: Passback/fallback wording fix

### ISSUE THREAD

**Issue by dmngdsm** [heyAuraDev/adex-platform#425]
**Is your feature request related to a problem? Please describe.**
We are using two different words for the same thing on publishers side. Let's choose either **passback** or **fallback** and leave it like that. (I'm voting for fallback)

![Screenshot 2020-04-07 at 15 45 59](https://user-images.githubusercontent.com/15030734/78671810-717d3c00-78e8-11ea-8734-a94c38bc5be0.png)

**Comment by ivopaunov** [comment]
it's all `passback` now
https://github.com/AdExNetwork/adex-translations/commit/f97cd86bd7ff81661a3f460a973f144ffcba7234
