### ISSUE TITLE
Integrate bannerflow

### ISSUE THREAD

**Issue by Ivshti** [heyAuraDev/adex-platform#443]
**Only an idea, not an important task yet**

**Describe the solution you'd like**
Integrate [bannerflow](https://www.bannerflow.com/) to make banner creation/integration easier.

This could happen in several ways:

- full widget to make banners if possible
- just an option to easily import banners as ad units

**Describe alternatives you've considered**
See #115

**Comment by rori4** [comment]
@Ivshti @dmngdsm 
I looked though bannerflow and bannersnack but there is no info on the site even how you should integrate it or even a demo.

Why don't we just integrate canva? It seems much more friendly to integrate and more people would be familiar with the tool
https://www.canva.com/button/

**Comment by dmngdsm** [comment]
> @Ivshti @dmngdsm
> I looked though bannerflow and bannersnack but there is no info on the site even how you should integrate it or even a demo.
> 
> Why don't we just integrate canva? It seems much more friendly to integrate and more people would be familiar with the tool
> https://www.canva.com/button/

In 2019 when I was researching it I found this https://docs.enterprise.bannersnack.com/getting-started/. I also had a call with bannersnack rep but don't remember much as we decided to leave the idea for later. Canva sounds reasonable - we've been pretty happy with it and you are right that majority of people are familiar with.

**Comment by rori4** [comment]
I saw those docs and I think it will be way more complicated then testing out Canva. Their integration looks very simple and easy to use. Can we fill the application and see what they reply? @Ivshti @dmngdsm

**Comment by dmngdsm** [comment]
> I saw those docs and I think it will be way more complicated the testing out Canva. Their integration looks very simple and easy to use. Can we fill the application and see what they reply? @Ivshti @dmngdsm

Sure, I'll submit an application.

**Comment by rori4** [comment]
Thanks :) @dmngdsm

**Comment by vanina-iv** [comment]
This is possibly related to https://github.com/AdExNetwork/aips/issues/37.

**Comment by dmngdsm** [comment]
> This is possibly related to [AdExNetwork/aips#37](https://github.com/AdExNetwork/aips/issues/37).

Totally. It's called Canva button now, but I guess it's similar. Rangel is working on the implementation at the moment.
