### ISSUE TITLE
publisher verification UX improvements

### ISSUE THREAD

**Issue by Ivshti** [heyAuraDev/adex-platform#445]
**Is your feature request related to a problem? Please describe.**
The verification process is still not smooth enough, judging from the fact users are still opening plenty of tickets.

There are a few problems:
- No clear indication that the user did everything they had to (no success message)
- If the verification fails due to DNS cache, there is no indication it might suceed later

**Describe the solution you'd like**
Some ideas to fix that:
- "website verification successful" message/popup
- popup that says  "there were some issues with your verification, please wait 24 hours" or something like that, in case it doesn't pass
- when you're creating an ad slot, the website field should be a dropdown with a "new website" option that turns it into an input - this will allow you to select from websites you previously added and are already verified; in this dropdown, we can have a green tick next to verified websites or a red cross next to ones that are failing; if you're a new user and there are no websites, it can just be an input field
- a "retry verification" button somewhere that will re-try the verification; or simply re-try verification every time the ad slot is saved; this is an incomplete idea, needs some brainstorming

@IvoPaunov @vanina-iv fee lfree to brainstorm and reassign the issue

**Comment by ivopaunov** [comment]
https://github.com/AdExNetwork/adex-platform/issues/429
