### ISSUE TITLE
Integrate JellySwap to exchange BTC for DAI.

### ISSUE THREAD

**Issue by kraikov** [heyAuraDev/adex-platform#452]
**Is your feature request related to a problem? Please describe.**
Enalbe users to buy DAI using BTC by integrating JellySwap via their public SDK.

**Describe the solution you'd like**
Use the public SDK by following the documentation here:
https://github.com/jelly-swap/jelly-monorepo/tree/master/packages/bitcoin
https://github.com/jelly-swap/jelly-monorepo/tree/master/packages/erc20

The links above describe how to initiate a swap from BTC and DAI. In the case of AdEx only BTC -> DAI swaps are going to be used.

For that purpose I've created a separate repository that will help you integrate BTC->DAI swaps.
https://github.com/jelly-swap/jelly-swap-adex

**Additional context**
1. You can match User's BTC swap with LP's DAI swap by the `hashLock` property (the swaps on both chains share the same hashLock).
2. You can use `getPastEvents` in order to load user's past swaps. From there on you can subscribe to real time event handling using `subscribe` (it's all described with example outputs in the documentation).
3. I'm available constantly so you can reach out to me and I'll help asap. Telegram @kraykov_jelly

**Comment by x5engine** [comment]
bounty? assign this to me? please?

**Comment by Ivshti** [comment]
closing as Changelly is working fine for now
we may reopen at some point

**Comment by x5engine** [comment]
very nice
