### ISSUE TITLE
Drop SAI migration code

### ISSUE THREAD

**Issue by Ivshti** [heyAuraDev/adex-platform#464]
**Describe the bug**
SAI on your account will currently count towards your overall balance, and will be migrated to DAI when you try to withdraw. This cannot work since SAI has been "emergency"-killed. 

**To Reproduce**
1. Have SAI in your account
2. Try to withdraw
3. It will fail; the backend error is `Vat/ceiling-exceeded`

**Solution**
Drop the SAI migration code altogether, stop counting SAI towards the balance.

Don't remove any generic code that can help AIP 20 (stablecoin agnostic UX)

**Comment by ivopaunov** [comment]
https://github.com/AdExNetwork/adex-platform/pull/465
