### ISSUE TITLE
UI: Platform fees tooltip when opening a campaign

### ISSUE THREAD

**Issue by dmngdsm** [heyAuraDev/adex-platform#473]
**Is your feature request related to a problem? Please describe.**
When you open a new campaign with the new UI you clearly see what fees you are about the pay. However, you just see a number, but no explanation. Of course, there's plenty of info on the website, but I doubt most of the advertisers are reading all the info before they start running ads - and they shouldn't.

**Describe the solution you'd like**
Include a small "i" tooltip near the Plaftorm fee field and when hover.

**Describe alternatives you've considered**
We can just add short explainer under the field

**Additional context**
![fees](https://user-images.githubusercontent.com/15030734/84380679-6ac4bb00-abf0-11ea-9537-36fd013d23b9.jpg)

**Comment by rori4** [comment]
related to #581
