### ISSUE TITLE
Incomplete Graph data for CPM & Revenue lines

### ISSUE THREAD

**Issue by TheBoroer** [heyAuraDev/adex-platform#481]
**Describe the bug**
In the Publisher Dashboard view, the CPM and revenue lines are incomplete/cut off for days/weeks in the past. The screenshot below shows an example of the graph showing data for June 22nd (2 days ago). This happens for any timeframe that I select (hour, day, week). 

**To Reproduce**
1. Go to publisher side of platform
2. Click on any day/week in the past (which should have a full 24 hours of reporting data)
3. See the incomplete graph line data

**Expected behavior**
I expected the full graph (all lines) to be visible for any timeframe in the past.

**Screenshots**
![image](https://user-images.githubusercontent.com/5162876/85504534-37a00580-b5ba-11ea-8d8a-85145da476a7.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: 83.0.4103.106

**Comment by Ivshti** [comment]
Related: #474 and probably many others

**Comment by ivopaunov** [comment]
Done with https://github.com/AdExNetwork/adex-platform/commit/fe1763f1b799d454fffa50216c36782501129bb8
