### ISSUE TITLE
UI review - recommendations

### ISSUE THREAD

**Issue by DimoStoyanov** [heyAuraDev/adex-platform#486]
### 1. Audience section
 
- [x] Item buttons should be "Edit", "Create New Campaign", "New Audience From This One", "Delete" (could be red button)
- [x] User should be able to edit the item Title

### 2. Dashboard

- [x] The _select period_ arrow is a bit misleading. Should be next to the item it controls.
<img width="450" heigh=**  alt="Screenshot 2020-07-02 at 14 53 37" src="https://user-images.githubusercontent.com/5999924/86453816-0b595700-bd27-11ea-960b-2c333368ced7.png">

- [x] Even though my campaign has ended 2 days ago, we still show statistics (maybe projection for impressions?)
<img width="450" height="240" alt="Screenshot 2020-07-03 at 12 21 55" src="https://user-images.githubusercontent.com/5999924/86454565-1791e400-bd28-11ea-83bd-f3feeb3be41e.png">

### 3 Ad unit

- [x] We should be able to delete ad units  
- [ ] Target URL should be editable, too (put button)

### 4. Campaigns section

- [ ] User should be able to delete campaigns
- [x] In general, we should consider redesigning the tabs system following original material design guidelines e.g.:
![Screenshot-2020-07-03-at-12 46 30](https://user-images.githubusercontent.com/5999924/86457122-d56aa180-bd2b-11ea-88bd-c9c5d3770be0.png)

**Create new campaign**
- [ ] On the audience step, we should be able to pick to create a new audience or use existing one
<img width="450" heigh=**  alt="Screenshot 2020-07-02 at 14 53 37" src="https://user-images.githubusercontent.com/5999924/86359495-bd3a4a00-bc79-11ea-9a96-0ee7192c02cf.png">

### View columns
- [x] should be able to remember the user's choice

**Comment by ivopaunov** [comment]
Deletion of items is duplicated issue: https://github.com/AdExNetwork/adex-platform/issues/93.
Actually it will be archive instead of delete, because of the relations between campaigns, units, audience and slots.
It will be possible to unarchive items as well.

**Comment by ivopaunov** [comment]
https://github.com/AdExNetwork/adex-platform/issues/492
