### ISSUE TITLE
Delete (archive and unarchive) item and controlled table filters and props

### ISSUE THREAD

**Issue by ivopaunov** [heyAuraDev/adex-platform#492]
User should be able to archive items (Campaigns, Units, Slots, Audiences). We need to make possible `unarchive` the items as well. We had this functionality in older versions but that was possible because we used our own controls that worked with data representation with tables and cards and whatever you want. The problem was the design which wasn't beautiful despite it's functionality. 

In order to be able to have `unarchive` option we need to control the currently used `mui-datatables` from the state. That can be tricky but will fix more problems as remembering the last page size selected for the specific table. Once we have controlled table we can have filters by item status (Active, Archived, All)

Keep the following steps:

- [x] 1. Make it possible to delete (archive) items - this can be done easy if we do not have filter on table, just filter all items in the 
selectors and show only the active once. (Campaigns only when everything is ready)
- [ ] 2. Make controls and filter of the data table controlled (using the state) - this may require changing the table package or making our own
- [ ] 3. Add filter for items status in the tables and `unarchive` action buttons (remove status filtering in items selectors)

Step 1 can be done now as it is not complex.

Related issues:
https://github.com/AdExNetwork/adex-platform/issues/486
https://github.com/AdExNetwork/adex-platform/issues/93
https://github.com/AdExNetwork/adex-platform/issues/356
https://github.com/AdExNetwork/adex-platform/issues/556

**Comment by Ivshti** [comment]
@IvoPaunov is this done?
