### ISSUE TITLE
Bugs to fix and improvement suggestions in v.4.20.28

### ISSUE THREAD

**Issue by vanina-iv** [heyAuraDev/adex-platform#497]
### 1. Replace text

When creating a new campaign, on step 3 ("Parameters") replace _You will see e.g."utm_source=AdEx+(publisheraddress.com)" at your Google Analytics_ with _You will see e.g."utm_source=AdEx (publisheraddress.com)" in Google Analytics_

![Screenshot 2020-07-14 at 14 40 49](https://user-images.githubusercontent.com/8737960/87423971-da5d0a00-c5e3-11ea-8eeb-e8dde7f821de.png)

### 2. Replace text
Change text on the pop-up for archiving an audience from _Once Audience is archived you will not see it the collection!_ to _Once Audience is archived you will not see it in your saved audiences_. 

![Screenshot 2020-07-14 at 15 03 41](https://user-images.githubusercontent.com/8737960/87424270-57887f00-c5e4-11ea-86c9-ffe2322a3412.png)

### 3. Change letter capitalization
On the Campaigns page, all statuses are capitalized, only "Completed" is in all caps; please capitalize it to match the others. 

![Screenshot 2020-07-14 at 15 01 35](https://user-images.githubusercontent.com/8737960/87424566-d54c8a80-c5e4-11ea-80d2-fa3478cf138f.png)

### 4. Clicking on an ad unit image when creating a new campaign should select it rather than opening the ad unit page, taking the user away from the campaign creation wizard. 

![Screenshot 2020-07-14 at 14 52 21](https://user-images.githubusercontent.com/8737960/87424623-f2815900-c5e4-11ea-80ee-d630634d2281.png)

### 5. Bug with publishers drop-down when replicating an audience
To replicate: 
1. Create a new audience from an existing one 
2. Get to the publishers dropdown
3. Scroll down
4. After a few seconds, the dropdown automatically scrolls up to the beginning 

Video here: https://share.getcloudapp.com/mXuA4APW

**Expected behavior**: Dropdown list shouldn't scroll back up

### 6. Bug with campaigns not spending when "Limit average daily spending" is selected
Some campaigns seem to be "stuck" and don't start spending. I've tried A/B testing to see what's the possible reason for this, and it seems that the culprit is the average daily spend limit. 

Example for a stuck campaign: https://jerry.moonicorn.network/channel/0xc892b8def2c6077504642390609a55283854ab05d55b31e585088d4f16b5e833/status

Replicated campaign with no average daily limit: https://jerry.moonicorn.network/channel/0x715a81bfa5b721620615fdcd5f6848bc2b042c492a2b9cbb7909601ae590d8fe/status

**Comment by ivopaunov** [comment]
5 and 6 are actually fixed, maybe the fixes are not in the build.
I'll leave 2 for now and 4 - it just will be inactive.

**Comment by vanina-iv** [comment]
No worries about 2 and 4 - 4 was just a suggestion anyway.
