### ISSUE TITLE
Login form: text should be "I agree to the Terms And Conditions"

### ISSUE THREAD

**Issue by Ivshti** [heyAuraDev/adex-platform#501]
**Describe the bug**
The checkbox for Terms and Conditions just says Terms and Conditions

**Solution**
Change it to "I have read and agree to the Terms and Conditions"

**Comment by ivopaunov** [comment]
https://github.com/AdExNetwork/adex-translations/commit/e623141f81d56a7ff31db77459d14d8dea6f6ae1
