### ISSUE TITLE
Add clearer instructions on the platform regarding adding new websites by publishers

### ISSUE THREAD

**Issue by dmngdsm** [heyAuraDev/adex-platform#506]
**Is your feature request related to a problem? Please describe.**

If you are new to the platform and just open the dashboard you'll see on your left "Ad Slots" and "Websites" menu items. Probably most people will go to "Websites" first, knowing that you have to add a website before you start with the slots themselves. But when you go to "Websites" this is all you'll see:
![image](https://user-images.githubusercontent.com/15030734/88297086-2c9adb00-cd08-11ea-8a33-be0ee9e2e252.png)

First: Although we have a [killer FAQ](https://help.adex.network/hc/en-us/articles/360012481519-How-to-add-DNS-TXT-record-for-your-publisher-domain) text on adding websites, there's no clue on this screen what you should do next, so some publishers will probably be WTF until they start looking for FAQs themselves.

Second: Adding DNS record involves some manual work like copy/pasting your Identity from your Account, then naming the DNS record, etc. We can make this process slightly easier and more idiotproof for publishers.

**Describe the solution you'd like**

On the "Websites" section there is a standard "Add Website" button. When you click it, a Window opens asking for the website domain and when you enter it, it generates DNS record to paste including your Identity ID and the rest of the stuff. 
There is also a warning explainer text that you also have to create an ad slot to pass verification.

**Describe alternatives you've considered**
Just this text slightly rewritten with link to the FAQ on the "Website " section
![Screenshot 2020-07-23 at 17 24 06](https://user-images.githubusercontent.com/15030734/88298055-5b658100-cd09-11ea-8906-080be2a0f344.png)

**Additional context**

**Comment by ivopaunov** [comment]
Website button is added with https://github.com/AdExNetwork/adex-platform/issues/529
