### ISSUE TITLE
Investigate possibility to integrate crypto.com payments system

### ISSUE THREAD

**Issue by TRtomasz** [heyAuraDev/adex-platform#531]
**Is your feature request related to a problem? Please describe.**
Additional top up integration system.

**Describe the solution you'd like**
Crypto.com offers mobile payment system  - https://pay-docs.crypto.com/ This perhaps could be integrated with adex.
It can also create possibilities for getting them on board :)

**Comment by rori4** [comment]
I have investigated this and I don't think it is suitable for us. Their payment button makes payment to USD/EUR/GBP etc for a producrt from your crypto wallet and we don't accept that. I don't see any way from their widget to send DAI to an address for example.

**Comment by rori4** [comment]
I don't see a way to integrate this. If someone sees one we can reopen it.

**Comment by rori4** [comment]
This might be possible after we implement V5. Will revisit this after we implement it.
