### ISSUE TITLE
Campaign targeting by User Agent/Device

### ISSUE THREAD

**Issue by dmngdsm** [heyAuraDev/adex-platform#535]
**Is your feature request related to a problem? Please describe.**
We have a pending advertiser who wants to work with us, but insists on being able to target users by device and run campaigns for users on mobile.

According to t[his](https://github.com/AdExNetwork/aips/issues/31) we should be able to include this type of targeting, but we have to think how it will look in the UI. 

**Describe the solution you'd like**

At least from a user/marketer POV I believe this should be available under Audiences - another tab called Devices/OS. The default will check all boxes, but users will be able to exclude options. No need of something fancier. 

Another thing we should consider - how it will look in campaign reports. Easier way: Overal stats for the campaign in %. Mobile - 35%, Desktop 20%, Tablet 45%. The best option will be under Stats by website to show % of the impressions per website distribution based on devices. I have no idea what other options we might try. 

**Describe alternatives you've considered**

**Additional context**

**Comment by vanina-iv** [comment]
How about we do something like this: 

![DEVICES](https://user-images.githubusercontent.com/8737960/91175233-2aea7b80-e6e9-11ea-9ffb-cc67e21df777.png)
