### ISSUE TITLE
can't edit CPM

### ISSUE THREAD

**Issue by Ivshti** [heyAuraDev/adex-platform#543]
**Describe the bug**
When a campaign is already created, it's not possible to edit the CPM

**To Reproduce**
1. Create a campaign
2. Try to edit the CPM

This might require more changes as `pricingBounds` needs to allow a higher range

**Other misc issues**
- The icon to edit a campaign is an eye rather than a pencil

**Comment by ivopaunov** [comment]
as campaign `spec.pricingBounds` can not be edited the pricingBounds should be part of targeting rules and audience input. `spec.pricingBounds` will be ... min - `userInput.min / 2`, max - `userInput.max * 2`. When user want to edit the CPMs `spec.pricingBounds` will be used for bounds for min and max. e.g user input `{ IMPRESSION: { min: 0.001, max: 8 } }` - `spec.pricingBounds={ { IMPRESSION: { min: 0.0005, max: 16 } }`
