### ISSUE TITLE
When closing Ad Unit Preview remain on the same page of ad units

### ISSUE THREAD

**Issue by dmngdsm** [heyAuraDev/adex-platform#556]
**Is your feature request related to a problem? Please describe.**
This is a very annoying situation right now. When you are browsing your ad units and you are like on a 2rd or 3rd page and you open an ad unit, you cannot close it and remain on the same page. You either hit "Back" or click on "Ad Units" but in either way it resets the pages and you have to start all over to get where you are

**Describe the solution you'd like**
Add "Close" button on Ad Unit preview. When you hit the button, you should remain where you were browsing ad units.

**Describe alternatives you've considered**
Of course, if you set "Show" to 100, perhaps you won't have this problem, but that's just a temporary solution.

**Additional context**

Screen recording of the issue: https://drive.google.com/file/d/1HXJzCwo1gI9-Vq0jwIibWLXAvAB_iH_D/view?usp=sharing

**Comment by ivopaunov** [comment]
It is related to controlled tables prop - https://github.com/AdExNetwork/adex-platform/issues/492
