### ISSUE TITLE
Campaign targeting: publisher selection: better filtering (active only)

### ISSUE THREAD

**Issue by ivopaunov** [heyAuraDev/adex-platform#557]
Currently it is possible to add targeting rule by publisher (hostname).
In the include only section are only filtered publishers which at this moment matching the flowing criteria:
- have earnings &&  have slots that matching the campaign ad units types &&  not blacklisted

The problem here is that some publishers may not be active anymore or the verified slot types are not integrated.
When some campaign has tight targeting it can stuck with no impressions.

We need some filter for publishers with slots that are currently active at the moment of campaign creation.
It can be achieved by getting some data from validators analytics (TODO what to use)

**Comment by ivopaunov** [comment]
Temp solution https://github.com/AdExNetwork/adex-market/pull/165 - it removed about 1/4 of the current publishers considered active before. However this does not guarantees  that all slot types of this publishers are active

**Comment by Ivshti** [comment]
Related #584 and https://github.com/AdExNetwork/aips/issues/64
