### ISSUE TITLE
Adex status webpage

### ISSUE THREAD

**Issue by TRtomasz** [heyAuraDev/adex-platform#559]
**Is your feature request related to a problem? Please describe.**
Show status of adex services, adex validators, adex api(?)

**Describe the solution you'd like**
We should have adexstatus.network webpage like other services
https://discordstatus.com/
https://www.githubstatus.com/
**Describe alternatives you've considered**

**Additional context**

**Comment by rori4** [comment]
we can use something like https://cachethq.io/

**Comment by rori4** [comment]
We can use an open source solution which can monitor the validators, relayer, websites etc. There are plenty: https://awesomeopensource.com/projects/statuspage

I personally like the https://github.com/statping/statping

@Ivshti what do you think?

**Comment by rori4** [comment]
an example status page has been implemented on https://status.adex.network/
I have tried to change the colors to our theme colors but the charts use hardcoded values and it looks ugly

**Comment by Ivshti** [comment]
seems to be done
