### ISSUE TITLE
GPL 3.0 licence conflicting with your TOS

### ISSUE THREAD

**Issue by VogtAI** [heyAuraDev/adex-platform#570]
Here in Github most of your repositories are licenced under GPL 3.0. However in your TOS at https://www.adex.network/tos/ it states under 10: 

`10. INTELLECTUAL PROPERTY RIGHTS ON THE WEBSITE

This site belongs to and is operated by AdEx. Each component of the Website and Platform and the layout itself, including but not limited to logos, trademarks, domain names, etc. which appear in any way on the Website or Platform, are protected by the current laws with subject intellectual property. Therefore, they belong strictly and solely to AdExand the use of any component is subject to prior authorisation...`

I'm no copyright lawyer, but isn't there a conflict?

**Comment by Ivshti** [comment]
It is not.

Copyright and license are two different things - while the ultimate copyright belogs to AdEx network as an entity, the license is open-source and permits other parties to modify it under the license terms. Those two things are not conflicting.

here's a reference: https://opensource.stackexchange.com/questions/297/whats-the-difference-between-copyright-and-licensing and an explanation: "Copyright is the legal term used to declare and prove who owns the intellectual property (the code, text, etc.). Licensing is the legal term used to describe the terms under which people are allowed to use the copyrighted material."
