### ISSUE TITLE
Allow advertisers to edit tiers or use both targeted and excluded countries at the same time

### ISSUE THREAD

**Issue by vanina-iv** [heyAuraDev/adex-platform#587]
**Is your feature request related to a problem? Please describe.**
When you set targeting for a campaign as an advertiser and you work with country tiers, you can't edit the tiers. For example, if you want to target Tier 1 but exclude just one country from it, that's not possible - the only way is add the countries from the tier one by one and that's insane. 

**Describe the solution you'd like**
I see two possible fixes for this: 

1. Allow advertisers to select both Target countries **and** excluded countries (right now you can select either one or the other but not both). 
2. Allow advertisers to edit the tiers - i.e. double click on the tier and have all the countries in it appear in the "Target countries field" separately.

**Comment by Ivshti** [comment]
3. ability to unfold a whole tier into the individual country pills contained in it

**Comment by vanina-iv** [comment]
> 1. ability to unfold a whole tier into the individual country pills contained in it

That's that I meant by 2. but you described it better.
