### ISSUE TITLE
Design the diversification modal dialog

### ISSUE THREAD

**Issue by Ivshti** [heyAuraDev/adex-platform#599]
It should be a modal which allows you to select 2 to 5 assets and % split between them. You get creative freedom on how that will happen, please propose a few options. 

One possible idea is to have a pie chart that you can resize the slices on, or a bar in which you can slide the allocations of each asset (hope that makes sense). There could be a separate button to add a different asset and a button on each asset to remove it.

**Comment by alesinka** [comment]
Here are some options - At first, starting with the dashboard (eventually):
![DeFi wallet UI dashboard - w sidebar](https://user-images.githubusercontent.com/24762344/119948804-e3f42400-bfa1-11eb-9d65-91c26147745a.png)
![DeFi wallet UI dashboard - allocation assets](https://user-images.githubusercontent.com/24762344/119948844-ef474f80-bfa1-11eb-9d51-78e9c9695787.png)
![DeFi wallet UI dashboard - allocation assets – 2](https://user-images.githubusercontent.com/24762344/119948855-f1111300-bfa1-11eb-9460-5d5c0897c248.png)
![DeFi wallet UI dashboard - allocation assets – 3](https://user-images.githubusercontent.com/24762344/119948863-f3736d00-bfa1-11eb-9685-c479e6524b1c.png)

And another type of graph - could be interactive by pulling the arrows, or smth like it... Even could be done directly on the dashboard, if not too much work :) Honestly, I don't like the square shape, but if we choose to have smth interactive, could be done in a more appropriate shape, just showing the concept:
![DeFi wallet UI dashboard - w sidebar – 1](https://user-images.githubusercontent.com/24762344/119949025-1dc52a80-bfa2-11eb-9400-bd57d39fa802.png)

**Comment by dmngdsm** [comment]
favorite one. looks similar to gitcoin's grants allocation UX which worked very good when I tested it 
![image](https://user-images.githubusercontent.com/15030734/119949540-a3e17100-bfa2-11eb-98fd-c26094440d1a.png)

**Comment by TRtomasz** [comment]
We could have some recommended presets like "Conservative" "Degen" "Risky". 
Here they have some indexes we can use as example https://indexed.finance/

**Comment by Ivshti** [comment]
@alesinka there should also be a smaller label under the "Allocate your assets"  which says "You are about to diversify <amount> <asset>", for example "You are about to diversify 10 ETH"

+1 for presets

**Comment by Ivshti** [comment]
also +1 for the one that @dmngdsm liked

**Comment by alesinka** [comment]
![DeFi wallet UI dashboard - allocation assets – 2](https://user-images.githubusercontent.com/24762344/120206502-eff71480-c233-11eb-8b4c-f849ac9786fa.png)

**Comment by Ivshti** [comment]
@alesinka about that - there wouldn't be diversification by protocol, only by assets
however, for each asset you should be able to choose whether you want to deposit in Aave or not

**Comment by alesinka** [comment]
@Ivshti this was given to me for the marketing needs. I thought there should be also a coin named AAVE :)
