### ISSUE TITLE
[Wallet] Add timeout for the user session

### ISSUE THREAD

**Issue by TRtomasz** [heyAuraDev/adex-platform#602]
**Is your feature request related to a problem? Please describe.**
At the moment user sessions has no timeout. So each time i open my browser even after few days i'm still logged to the wallet. This could be a security threat for users 
**Describe the solution you'd like**
Users should be logged out after some inactivity time.
Best solution would be to make this configurable by user
**Describe alternatives you've considered**

**Additional context**

**Comment by Ivshti** [comment]
Not relevant in ambire-wallet, cause the session does not remember the password
