### ISSUE TITLE
Set http links to "invalid format" for advertisers

### ISSUE THREAD

**Issue by Vesi5** [heyAuraDev/adex-platform#611]
Currently when advertisers create an ad unit they can add http links as a url. The link cannot be open from the quick access button in the "Creating ad unit" section (Paunov confirmed that this button is currently set to transform all http urls to https and it is not working properly for websites that do not have https), but http links are accepted and actually working when a campaign is created. This is a bit confusing for advertisers, since when checking if the link is working when creating an ad unit, the link does not open (due to the http to https automatic transformation described above), but it is actually accepted by the platform at a later stage.

From a security point of view it would be best to accept only https as urls from advertisers and add an automatic check for https links + an invalid format warning (as shown in the screenshot below for publishers). 

<img width="1363" alt="Screenshot 2021-09-08 at 15 07 01" src="https://user-images.githubusercontent.com/64790881/132688629-65f2f687-2cdb-4d8f-9cc0-28150c3c6fb0.png">

**Comment by Ivshti** [comment]
@Vesi5 that''s bad UX cause some people may not notice "https" vs "http" and might not figure out what's wrong

The error message should be "only HTTPS websites accepted" or something more obvious like that
